# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5ddb6ba14a7a8c4bb0c19be011ee5752041ebfb67d6de9d97f17916f15cd1a0da24000f0956f35ba7a76cf4e4f5c5a49bf713a375d18e0f713543736f5fbc2e

test:
  secret_key_base: 881c44cca05cb45c95cb4022e7d879321ddb06a305c13b29743b22c55730c936469028c5b7021e2e7eacb440a06918b9e822f899457f6536194778625acc2767

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
